.PHONY: clean All

All:
	@echo "----------Building project:[ Console - Debug ]----------"
	@cd "Console" && "$(MAKE)" -f  "Console.mk"
clean:
	@echo "----------Cleaning project:[ Console - Debug ]----------"
	@cd "Console" && "$(MAKE)" -f  "Console.mk" clean
